# 公共配置文件
# @author PYW
# @from www.panyuwen.top
spring:
  application:
    name: gigotapi-backend
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
#  session:
#    # todo 取消注释开启分布式 session（须先配置 Redis）
#    # store-type: redis
#    # 30 天过期
#    timeout: 2592000
  # 数据库配置
  # 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gigot_api
    username: # todo 数据库用户名
    password: # todo 数据库密码
  # Redis 配置
  redis:
    database: 1
    host: # todo redis地址
    port: # todo redis端口号
    timeout: 5000
    password: # todo redis密码
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8001 # todo 端口号
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
logging:
  level:
    root: INFO
# 以下配置指定了应用的名称、使用的协议（Dubbo）、注册中心的类型（Nacos）和地址
dubbo:
  application:
    name: dubbo-gigotapi-provider # Dubbo名称
  # 指定使用 Dubbo 协议，且端口设置为 -1，表示随机分配可用端口
    qosPort: 28011
  protocol:
    name: dubbo # todo Dubbo protocol名称
    port: 28001 # todo Dubbo protocol端口号

  registry:
    # 配置注册中心为 Nacos，使用的地址是 nacos://localhost:8848
    id: nacos-registry # todo 注册中心id
    address: nacos://localhost:8848 # 注册中心地址

# todo 需替换配置
## 微信相关
wx:
  # todo 微信支付
  pay:
    # 商户号
    mchId:
    # 商户Api序列号
    mch-serial-no:
    # 商户私钥文件
    private-key-path:
    # APIv3秘钥
    api-v3-key:
    # 微信小程序/公众号/服务号id
    app-id:
    # 微信服务器地址
    domain:
    # 接收支付结果地址
    notify-domain:
  # todo 微信公众平台
  mp:
    token: xxx
    aesKey: xxx
    appId:
    secret:
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 腾讯云
tencent-cloud:
  sms:
    # 腾讯云用户api密钥
    secret-id:
    secret-key:
    # 签名id
    sdk-app-id:
    # 模板id
    template-id:
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey:
    secretKey:
    region:
    bucket:
# todo 羊腿api开放平台
gigot-api:
  upload:
    # 头像存放地址
    avatarUrlFilePath: "src/main/resources/static/img/avatarUrl"
    # api接口地址
    apiUrl: "http://localhost:8001"
  client:
    # 开放平台密钥
    secret-id:
    secret-key:
  # 发邮箱相关配置
  mail:
    user:
    password:
  # SDK存放地址 用于提供给用户SDK下载
  sdk:
    download: "src/main/resources/static/sdk/gigotapi-client-sdk-0.0.3.jar"